### ISSUE TITLE
Fluid Blocks Flow During Tick Freeze and Entities Move at Normal Speed During Tick Advance

### ISSUE THREAD

**Issue by Etrainquandt17** [MinecraftTAS/LoTAS-Light#17]
Self explanatory.

**Comment by PancakeTAS** [comment]
?!?

are you talking about the animation or the actual fluids?

**Comment by Etrainquandt17** [comment]
The actual fluids. The animations actually do freeze. I can provide a video if needed.

**Comment by PancakeTAS** [comment]
a video would be a amazing, because I've never seen a bug like this ever before. this is really surprising, lol.

**Comment by ScribbleTAS** [comment]
Just tested it, server side is not tick advancing correctly... thought I fixed that ._.
