### ISSUE TITLE
Horizontal Mouse Movement is Slowed in Vehicles

### ISSUE THREAD

**Issue by Etrainquandt17** [MinecraftTAS/LoTAS-Light#18]
https://github.com/user-attachments/assets/1cbbc09b-4a10-413c-8d74-b616fff5b2cb

**Comment by ScribbleTAS** [comment]
Really interesting, this is a vanilla bug and is not related to LoTAS-Light... I think sitting on horses syncs your movement to the server tickrate in a way and this happens...
